### ISSUE TITLE
Please provide information about commercial usage.

### ISSUE THREAD

**Issue by shinchit** [mnmandahalf/mask-slack-icons-and-names#3]
Hello,

Thank you for developing this wonderful tool.

I have a question.

Regarding the icons of various animals used after conversion with this tool, is commercial usage possible? I would like to use the results masked with this tool in a presentation for a certain video. I want to make sure there are no licensing issues before proceeding.

I apologize for reaching out while you're likely busy, but I would greatly appreciate your response.

Regards,

**Comment by mnmandahalf** [comment]
Hello @shinchit,

Sorry it took me so long to notice.

You can use the results generated by this tool for commercial purposes.
 However, please follow the rules stated here for the use of icon materials.
 http://flat-icon-design.com/?page_id=41

https://github.com/mnmandahalf/mask-slack-icons-and-names?tab=readme-ov-file#about-commercial-use-of-icon-materials
